package wikiparse

import (
	"reflect"
	"testing"
)

func TestLinkSearch(t *testing.T) {
	exp := []string{"Aplysina archeri",
		"Robert Edmund Grant",
		"Robert Bentley Todd",
		"Calcarea",
		"Hexactinellida",
		"Demospongiae",
		"Homoscleromorpha",
		"animal",
		"phylum",
		"mesohyl",
		"Cell (biology)",
		"nervous system",
		"digestive system",
		"circulatory system",
		"osculum",
		"Sessility (zoology)",
		"bacteria",
		"photosynthesis",
		"endosymbiont",
		"carnivore",
		"crustacean",
		"sexual reproduction",
		"sperm",
		"ovum",
		"larva",
		"gemmule",
		"endoskeleton",
		"Biomineralization",
		"sponge spicule",
		"spongin",
		"Demosponge",
		"silica",
		"calcium carbonate",
		"exoskeleton",
		"Calcareous sponge",
		"glass sponge",
		"scaffolding",
		"Archaeocyathid",
		"unicellular",
		"choanoflagellate",
		"monophyletic",
		"Eumetazoa",
		"Homoscleromorpha",
		"Ctenophora",
		"phylum",
		"Sessility (zoology)",
		"metazoa",
		"choanocyte",
		"cnidaria",
		"ctenophore",
		"ar:إسفنجيات",
		"az:Süngərlər",
		"ba:Болоттар",
		"be:Губкі",
		"be-x-old:Губкі",
		"bg:Водни гъби",
		"bs:Porifera (spužve)",
		"br:Spoue",
		"ca:Porífer",
		"cs:Houbovci",
		"cy:Sbwng",
		"da:Svampedyr",
		"de:Schwämme",
		"nv:Táłtłʼááh yilcháazhii",
		"et:Käsnad",
		"el:Σπόγγος",
		"es:Porifera",
		"eo:Spongulo",
		"eu:Belaki",
		"fa:اسفنج دریایی",
		"fr:Porifera",
		"gv:Porifera",
		"gl:Poríferos",
		"ko:해면동물",
		"hi:स्पंज",
		"hr:Spužve",
		"io:Sponjo",
		"id:Porifera",
		"is:Svampdýr",
		"it:Porifera",
		"he:ספוגיים",
		"jv:Porifera",
		"kk:Губкалар",
		"ku:Parazoa",
		"la:Porifera",
		"lv:Sūkļi",
		"lb:Schwämm (Déieren)",
		"lt:Pintys",
		"hu:Szivacsok",
		"mk:Сунѓери",
		"my:စပန်းရေမြှုပ်",
		"nl:Sponsdieren",
		"ja:海綿動物",
		"frr:Swaampen (weederdiarten)",
		"no:Svamper",
		"nn:Svampar",
		"oc:Porifera",
		"pl:Gąbki",
		"pt:Porifera",
		"ro:Spongieri",
		"qu:Puqyala",
		"ru:Губки",
		"sq:Sfungjeri",
		"simple:Sponge",
		"sk:Hubky",
		"sl:Spužve",
		"sr:Сунђери",
		"sh:Spužve",
		"fi:Sienieläimet",
		"sv:Svampdjur",
		"ta:பஞ்சுயிரி",
		"te:స్పంజిక",
		"th:ฟองน้ำ",
		"tr:Süngerler",
		"uk:Губки",
		"vi:Bọt biển",
		"diq:Sunger",
		"zh:多孔动物门",
	}
	found := FindLinks(sponge)

	if !reflect.DeepEqual(exp, found) {
		t.Fatalf("Expected %#v, got %#v", exp, found)
	}
}
